name: Create K8S on EKS

on:
  repository_dispatch:
    types: [trigger-deploy]

env:
  EKS_CLUSTER_NAME: fiap_fast_food_eks
  AWS_REGION: us-east-1

jobs:

  build:

    name: Deployment
    runs-on: ubuntu-latest

    steps:

      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.30.2'
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Destroying EKS
        run: |
          kubectl delete --ignore-not-found=true -f infra/cm/.
          kubectl delete --ignore-not-found=true -f infra/secrets/.
          kubectl delete --ignore-not-found=true -f infra/deployment/.

      - name: Recreating EKS
        run: |
          kubectl apply --validate=false -f infra/cm/.
          kubectl apply --validate=false -f infra/secrets/.
          kubectl apply --validate=false -f infra/deployment/.
          kubectl apply --validate=false -f infra/hpa/.
          kubectl apply --validate=false -f infra/svc/.
